### ISSUE TITLE
Extending js and css helpers

### ISSUE THREAD

**Issue by doowb** [assemble/handlebars-helpers#102]
We've been considering ways to make it easy to include script and stylesheet resources from pages and partials/components, but make sure those resources are injected into the html in the correct place (usually being a layout).

I'm opening this issue to get some ideas on how it would look in handlebars syntax so I can try to get it working as a helper.

`data.yml`:
```yml
listOfCssOrLessFiles:
 - file1.css
 - file2.css
 - file3.css

listOfJavaScriptFiles:
 - file1.js
 - file2.js
 - file3.js

additionalCssFiles:
 - addtionalFile1.css

additionalJsFiles:
 - additionalFile1.js
```

`Layout.hbs`:
```handlebars
<html>
  <head>
    {{css listOfCssOrLessFiles}}
  </head>
  <body>
    {{> body}}
    {{js listOfJavaScriptFiles}}
  </body>
</html>
```

`Page1.hbs`:
```handlebars
<h1>Awesome Component Example</h1>
<div id="myComponent"></div>
{{css additionalCssFiles}}
{{js additionalJsFiles}}
```

This would allow only loading the files that are needed for the current page being built. The results would be like this...
`Page1.html`
```html
<html>
  <head>
    <link rel="stylesheet" href="assets/styles/file1.css">
    <link rel="stylesheet" href="assets/styles/file2.css">
    <link rel="stylesheet" href="assets/styles/file3.css">
    <link rel="stylesheet" href="assets/styles/additionalFile1.css">
  </head>
  <body>
    <h1>Awesome Component Example</h1>
    <div id="myComponent"></div>
    <script src="assets/js/file1.js"></script>
    <script src="assets/js/file2.js"></script>
    <script src="assets/js/file3.js"></script>
    <script src="assets/js/additionalFile1.js"></script>
  </body>
</html>
```

Please post ideas or a better syntax for these helpers. Thanks.
